# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Atribute_Connect
                                 A QGIS plugin
 Xây dựng Plugin đọc và liên kết bảng dữ liệu thuộc tính với 1 lớp dữ liệu không gian
(vector) có sẵn và export ra bảng dữ liệu mới với các thuộc tính liên kết để thống kê báo cáo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-14
        copyright            : (C) 2024 by Group2
        email                : giangvanhung2003@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Atribute_Connect class from file Atribute_Connect.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Atribute_Connect import Atribute_Connect
    return Atribute_Connect(iface)
