# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Atribute_ConnectDialog
                                 A QGIS plugin
 Xây dựng Plugin đọc và liên kết bảng dữ liệu thuộc tính với 1 lớp dữ liệu không gian
(vector) có sẵn và export ra bảng dữ liệu mới với các thuộc tính liên kết để thống kê báo cáo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-14
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Group2
        email                : giangvanhung2003@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import pandas as pd

from qgis.PyQt.QtWidgets import QDialog
from qgis.PyQt import uic, QtWidgets
from qgis.core import QgsVectorLayer, QgsProject, QgsField
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QFileDialog, QTableWidget, QTableWidgetItem, QVBoxLayout, QWidget

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Atribute_Connect_dialog_base.ui'))


class Atribute_ConnectDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(Atribute_ConnectDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.pushButton_2.clicked.connect(self.select_vector_layer)
        self.pushButton_3.clicked.connect(self.select_attribute_table)
        #self.btn_export.clicked.connect(self.export_result)

    def select_vector_layer(self):
        """Chọn lớp dữ liệu không gian (Vector)."""
        vector_layer, _ = QFileDialog.getOpenFileName(self, "Chọn lớp dữ liệu không gian", "", "All files (*);;GeoJSON files (*.geojson);;Shapefiles (*.shp)")
        if vector_layer:
            # self.lineEdit.setText(vector_layer)  # Hiển thị đường dẫn file vào UI
            
            # Tạo lớp không gian từ file .shp hoặc .geojson
            layer = QgsVectorLayer(vector_layer, "Layer", "ogr")
            
            # Lấy các trường của lớp không gian và hiển thị trong combobox
            fields = layer.fields()
            self.tableWidget_2.setRowCount(0)
            self.comboBox.clear()  # Xóa các mục cũ trong comboBox
            for field in fields:
                self.comboBox.addItem(field.name())
            self.show_tableWidget(layer)

    def select_attribute_table(self):
        """Chọn bảng dữ liệu thuộc tính."""
        attribute_table, _ = QFileDialog.getOpenFileName(self, "Chọn bảng dữ liệu thuộc tính", "", "All files (*);;CSV files (*.csv);;Excel files (*.xlsx,*.xls)")
        if attribute_table:
            if attribute_table.endswith('.csv'):
                self.attribute_data = pd.read_csv(attribute_table)
            elif attribute_table.endswith('.xlsx') or attribute_table.endswith('.xls'):
                self.attribute_data = pd.read_excel(attribute_table, engine='xlrd') 
            else:
                QtWidgets.QMessageBox.warning(self, "Lỗi", "Chỉ hỗ trợ định dạng CSV và Excel.")
                return
            if self.attribute_data is not None and not self.attribute_data.empty:
                self.show_attribute_table()
            else:
                QtWidgets.QMessageBox.warning(self, "Lỗi", "Bảng dữ liệu thuộc tính trống.")

    def export_result(self):
        """Xử lý xuất kết quả thống kê."""
        # Gọi hàm thống kê và xuất dữ liệu ở đây
        pass

    def show_tableWidget(self, layer):
        """Hiển thị bảng dữ liệu thuộc tính của lớp không gian."""
        # Lấy dữ liệu thuộc tính từ lớp
        fields = layer.fields()
        features = layer.getFeatures()

        # Tạo một QTableWidget để hiển thị bảng
        self.tableWidget_2.setRowCount(0)  # Không có dòng ban đầu
        self.tableWidget_2.setColumnCount(len(fields))  # Số cột bằng số trường dữ liệu

        # Thiết lập tiêu đề cột
        self.tableWidget_2.setHorizontalHeaderLabels([field.name() for field in fields])

        # Thêm dữ liệu vào bảng
        for feature in features:
            row_position = self.tableWidget_2.rowCount()
            self.tableWidget_2.insertRow(row_position)
            for col, field in enumerate(fields):
                # Lấy giá trị từ trường của đối tượng
                value = feature[field.name()]
                # Thêm dữ liệu vào ô bảng
                self.tableWidget_2.setItem(row_position, col, QTableWidgetItem(str(value)))

    def show_attribute_table(self):
        """Hiển thị bảng dữ liệu thuộc tính vào tableWidget."""
        if self.attribute_data is not None:
            self.tableWidget.setRowCount(0)  # Xóa tất cả dòng hiện tại trong tableWidget_2
            for index, row in self.attribute_data.iterrows():
                row_position = self.tableWidget.rowCount()
                self.tableWidget.insertRow(row_position)
                for col, value in enumerate(row):
                    self.tableWidget.setItem(row_position, col, QtWidgets.QTableWidgetItem(str(value)))
